### ISSUE TITLE
Crash in File Picker

### ISSUE THREAD

**Issue by StereoMadnessss** [hippogamesunity/PixelStudioHub#137]
Pixel Studio in my eyes is a great way to start making images and photos with it's great array of assorted features that it provides like palettes, shape drawing, and the easy to use interface that it has. However every now and then comes a major issue that crushes the entire application of its goodness and every now and then can drive people away from certain apps entirely. Further leading why, we need to go back to an issue that I made a while ago where I noted that Pixel Studio was going downhill in a certain way directed towards people who want to export files to their file system and not upload them to the storage. This issue is a perfect way to represent where this is going. This bug is most likely the most annoying bug to ever exist in Pixel Studio so here it is. Open Pixel Studio, make something that you don't care about and open an image from files and when you click open, Pixel Studio should immediately crash. If you try saving to files, you get the same result. As a whole, this further proves my point that even to a basic users perspective, they can see this crash occur, even by accident. Here is me showing the issue (the 3d modeling screen is there to show that it crashed

https://user-images.githubusercontent.com/77188051/165434413-ef351ddb-87fb-4d2f-adb5-5d13f9251d05.mp4

)
Besides it being compressed quite a lot, this is reproducible on any version of Pixel Studio (confirmation needed)

**Comment by hippogamesunity** [comment]
Hi! Thanks for letting us know and sorry for this bug. We're working on it and will do our best to fix it asap.

**Comment by StereoMadnessss** [comment]
I hope this gets fixed soon

**Comment by StereoMadnessss** [comment]
still in effect? this is very annoying and this should be fixed already.

**Comment by hippogamesunity** [comment]
Hi, the new update is in deployment.

вт, 17 мая 2022 г., 07:03 StereoMadnessss ***@***.***>:

**Comment by hippogamesunity** [comment]
Unfortunately, the issue was not fixed. While it works before we upload it to the App Store, it starts crashing after processing by the App Store.

**Comment by StereoMadnessss** [comment]
could I have the app if possible if the app store makes it crash?

**Comment by StereoMadnessss** [comment]
I have had enough. This issue is done.

**Comment by hippogamesunity** [comment]
Hi! Unfortunately we still can't fix this bug. Now this feature doesn't work on some MacOS versions. So we have to shut it down by now and keep finding for another solution. Sorry for this inconvenience.
